import { readFile, writeFile } from "node:fs/promises";
import process from "node:process";
import prettier from "prettier";

const sbomPath = process.argv[2];
const checkOnly = process.argv.includes("--check");
if (!sbomPath)
  throw new Error(
    "Usage: node scripts/generate-notices.mjs <sbom.cdx.json> [--check]",
  );

const sbom = JSON.parse(await readFile(sbomPath, "utf8"));
const components = [...(sbom.components ?? [])].sort((a, b) =>
  `${a.name}@${a.version}`.localeCompare(`${b.name}@${b.version}`),
);
if (!components.length)
  throw new Error("The runtime SBOM has no components for notices.");

const escape = (value) => String(value).replaceAll("|", "\\|");
const license = (component) =>
  component.licenses
    ?.map((entry) => entry.license?.id ?? entry.license?.name)
    .filter(Boolean)
    .join(", ") ?? "See package metadata";
const source = (component) =>
  component.externalReferences?.find((entry) =>
    ["vcs", "website", "documentation"].includes(entry.type),
  )?.url ??
  component.purl ??
  "Bundled component";

const lines = [
  "# Third-party notices",
  "",
  "<!-- Generated by scripts/generate-notices.mjs from the validated runtime SBOM. -->",
  "",
  "Upright bundles the following runtime components. This inventory is generated from the pinned production dependency graph and bundled model; CI fails if it becomes stale.",
  "",
  "| Component | Version | License | Source |",
  "| --- | --- | --- | --- |",
  ...components.map(
    (component) =>
      `| ${escape(component.name)} | ${escape(component.version)} | ${escape(license(component))} | ${escape(source(component))} |`,
  ),
  "",
  "Electron distributions also carry Chromium and other upstream notices inside the packaged runtime. MediaPipe camera processing remains local to Upright.",
  "",
];
const expected = await prettier.format(lines.join("\n"), {
  parser: "markdown",
});
const output = "THIRD_PARTY_NOTICES.md";

if (checkOnly) {
  const current = await readFile(output, "utf8");
  if (current !== expected)
    throw new Error(
      `${output} is stale. Run node scripts/generate-notices.mjs ${sbomPath}.`,
    );
  console.log(`${output} matches the validated runtime inventory.`);
} else {
  await writeFile(output, expected, "utf8");
  console.log(
    `Generated ${output} from ${components.length} runtime components.`,
  );
}
